# Site settings
title: UAV Stats
description: >
  Statistics and reports regarding Unmanned Aerial Vehicles (UAV) or Unmanned Aerial Systems (UAS, sUAS)
baseurl: "/"

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate]

# comments
disqus: uavstats

# author info
author: Daniel James
bio:    # your bio
email: uavstats@thzinc.com
email_md5: 690c60e5c42ee3872f16e948c14ba28a
twitter_username: "@thzinc"
github_username: uav-stats

# Theming options
# These settings are mandatory.
theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
